### ISSUE TITLE
Function getByName() for Images always returns x86 image

### ISSUE THREAD

**Issue by elindydotcom** [LKDevelopment/hetzner-cloud-php-sdk#110]
The function getByName() in the images model always returns the first value which is usually the x86 image.

Since you can now get two images from the same name (one for arm and one for x86), one of two things might need to be changed:

- The function signature needs to change and include a parameter for the architecture with the default being 'x86' if no parameter is passed for the second value (which preserves backward compatibility with existing code).
- A new function needs to be created that returns both image objects.

Maybe both needs to be done?

OR, the image names need to be changed - eg: 'ubuntu-22.04' and 'ubuntu-22.04-arm' but that would have to be done by Hetzner's ops team.  So likely more practical to implement one or both the options above?

**Comment by LKaemmerling** [comment]
Hey @elindydotcom,

thank you, good catch! I added a new (optional) parameter to the GetByName Method on Images. This was just released as v2.7.0.
