### ISSUE TITLE
Fatal error in Symfony 7, due to `tightenco/collect`

### ISSUE THREAD

**Issue by ThomasLandauer** [LKDevelopment/hetzner-cloud-php-sdk#113]
After upgrading to Symfony 7.0, I'm getting:

> Fatal error: Type of Tightenco\Collect\Support\Debug\HtmlDumper::$styles must be array (as in class Symfony\Component\VarDumper\Dumper\CliDumper) in vendor/tightenco/collect/src/Collect/Support/Debug/HtmlDumper.php 
on line 7

This is probably due to Symfony's more restrictive type handling in v7.

I was able to fix it by adding `array` at https://github.com/tighten/collect/blob/laravel-5.6-ongoing/src/Collect/Support/Debug/HtmlDumper.php#L14 :

```php
protected array $styles = [
```
So either upgrading or removing `tightenco/collect` (as I already suggested at https://github.com/LKDevelopment/hetzner-cloud-php-sdk/issues/79) is more urgent now :-)

**Comment by LKaemmerling** [comment]
Fixed with the last version
