### ISSUE TITLE
Use illuminate/collections instead of tightenco/collect

### ISSUE THREAD

**Issue by Cannonb4ll** [LKDevelopment/hetzner-cloud-php-sdk#115]
Error description:

```
Package tightenco/collect is abandoned, you should avoid using it. Use illuminate/collections instead.
```

I'd love to push a PR, considering all the PR's made by the community being left open I start with an issue. If you want me to PR this, please let me know.

**Comment by LKaemmerling** [comment]
Was released with the latest version.
