### ISSUE TITLE
Missing setting for created field in setAdditionalData

### ISSUE THREAD

**Issue by ygrenne** [LKDevelopment/hetzner-cloud-php-sdk#19]
$created field is missed https://github.com/LKDevelopment/hetzner-cloud-php-sdk/blob/master/src/Models/Servers/Server.php#L44  in https://github.com/LKDevelopment/hetzner-cloud-php-sdk/blob/master/src/Models/Servers/Server.php#L131 

must be added:
`$this->created = $data->created;`

**Comment by LKaemmerling** [comment]
Yep you are right, was fixed with v1.6.2

**Comment by ygrenne** [comment]
Thanks
