### ISSUE TITLE
Describe requests missing

### ISSUE THREAD

**Issue by fliespl** [LKDevelopment/hetzner-cloud-php-sdk#38]
Would be great if this script could also handle describe commands :)

hcloud server describe NAME
hcloud floating-ip describe NAME

getByName could utilize it

**Comment by LKaemmerling** [comment]
As this is an PHP library it does not support commands, you can use the library to create a commandline Interface. 

The specific commands you requested are already part of the official Hcloud Cli: https://github.com/hetznercloud/cli

**Comment by fliespl** [comment]
You are totally right - I didn't look properly how getByName works :)

Thanks!
