### ISSUE TITLE
Undefined property stdClass $recommendation

### ISSUE THREAD

**Issue by SamuelNitsche** [LKDevelopment/hetzner-cloud-php-sdk#4]
Beim holen aller Datacenters bekomme ich folgenden Fehler
`
PHP Notice:  Undefined property: stdClass::$recommendation in /vendor/lkdevelopment/hetzner-cloud-php-sdk/src/Models/Datacenters/Datacenter.php on line 85
`

```
$hetznerClient = new HetznerAPIClient($user->hetzner_api_token);
$datacenterClient = new Datacenters();
$hetzner_datacenters = $datacenterClient->all();
```

[EDIT]
Ich habe mir kurz den Code sowie die Hetzner API Docs angeschaut. Das Object "datacenter" in der Hetzner API Antwort enthält kein Property "recommendation". Dieses Property existiert nur im Object "datacenters". An dieser Stelle müsste dein Code geupdatet werden.

**Comment by LKDevelopment** [comment]
Wurde angepasst :) Vielen Dank! Die neue Version 0.0.9 enthalt den Fix.
