### ISSUE TITLE
Create Server Error:  Argument 1 passed to.... must be an instance of ...

### ISSUE THREAD

**Issue by entttom** [LKDevelopment/hetzner-cloud-php-sdk#45]
Hallo,
ich versuche auf  nem Server mit Ubuntu 18.04, Apache2 und php 7.2 einen Server zu erstellen mit dem example script und bekomme leider folgende Fehlermeldung die mich völlig ratlos zurück lässt.
Denn alle anderen examples funktionieren wunderbar.

`PHP Fatal error:  Uncaught TypeError: Argument 1 passed to LKDev\HetznerCloud\Models\Locations\Locations::all() must be an instance of LKDev\HetznerCloud\RequestOpts or null, string given, called in /home/tom/hetzner_test_php/hetzner_server_erstellen.php on line 10 and defined in /home/tom/hetzner_test_php/vendor/lkdevelopment/hetzner-cloud-php-sdk/src/Models/Locations/Locations.php:35
Stack trace:
#0 /home/tom/hetzner_test_php/hetzner_server_erstellen.php(10): LKDev\HetznerCloud\Models\Locations\Locations->all('fsn1')
#1 {main}
  thrown in /home/tom/hetzner_test_php/vendor/lkdevelopment/hetzner-cloud-php-sdk/src/Models/Locations/Locations.php on line 35`

Kann sich jemand erklären wie das Zustande kommt?
Danke! :)

**Comment by LKaemmerling** [comment]
Hey, sorry für die späte Rückmeldung, ich war ziemlich beschäftigt mit dem Load Balancer launch.

Die Beispiele sind nicht mehr vollständig korrekt. Ich werden sie sofort anpassen. Danke für die Meldung!

**Comment by LKaemmerling** [comment]
Behoben mit bd68629
