### ISSUE TITLE
Problem with requestConsole()

### ISSUE THREAD

**Issue by RamonSmit** [LKDevelopment/hetzner-cloud-php-sdk#5]
Hi there, 

Thanks for this awesome package! 

I have a slight problem to get the websocket url and password from the package. 
In the code i execute: 

```php
$hetznerClient = new \LKDev\HetznerCloud\HetznerAPIClient(getenv('HCLOUD_TOKEN'));
$server = (new \LKDev\HetznerCloud\Models\Servers\Servers())->get(xxxxx);
var_dump($server->requestConsole());
```

I expected to get a `wss_url` and `password` but instead i'm only getting:
```
LKDev\HetznerCloud\Models\Actions\Action {#1613
     +id: xxxxx,
     +command: "request_console",
     +progress: 100,
     +started: "success",
     +finished: "2018-04-22T09:22:39+00:00",
     +resources: "2018-04-22T09:22:39+00:00",
     +error: [
       {#1557
         +"id": xxxxx,
         +"type": "server",
       },
     ],
     +root_password: null,
   }
```

Can you help me out for a bit with this? 

Thanks in advance

Ramon

**Comment by LKDevelopment** [comment]
Hello Ramon,

i've updated the file in the master branch, could you please check it out and test if it now works? I'll publish the update then :)

Hello Ramon,

i've updated the file in the master branch, could you please check it out and test if it now works? I'll publish the update then :)

**Comment by RamonSmit** [comment]
Hi! 

Seems to work if i remove the return type Action
`TypeError: Return value of LKDev/HetznerCloud/Models/Servers/Server::requestConsole() must be an instance of LKDev/HetznerCloud/Models/Actions/Action, instance of stdClass returned`

Other then that, it works! :-) 

Might me a tip:

You're using 
`json_decode((string) $response->getBody())` on multiple locations, Isn't it nicer to use `json_decode($response->getBody()->getContents())`? 

Thanks, 
Ramon

**Comment by LKDevelopment** [comment]
Hey,

the type bug is fixed :)

I'll release it in a couple of minutes.


Yeah this is basicly the same, but i think with the (string) cast it is a little bit cleaner, shorter and readabler.
