### ISSUE TITLE
How to get the reset Password?

### ISSUE THREAD

**Issue by ClayHostDE** [LKDevelopment/hetzner-cloud-php-sdk#55]
I developed a Module and use the function $server->resetRootPassword();.

How to Print the Password?

**Comment by LKaemmerling** [comment]
You get a normal response from this method, so you should just get the password by using:

```php
$response = $server->resetRootPassword()
var_dump($response->getResponsePart('root_password'));

**Comment by ClayHostDE** [comment]
ok thank you very much.

**Comment by ClayHostDE** [comment]
Can i set a custom password with this method?

**Comment by LKaemmerling** [comment]
No, actually please read the documentation of the Hetzner Cloud API. This SDK is just a wrapper for the API calls.
