### ISSUE TITLE
server->createImage without label not working

### ISSUE THREAD

**Issue by hholzer** [LKDevelopment/hetzner-cloud-php-sdk#56]
der code:
$server->createImage('testimage'));

führt bei hetzner zu den fehler: invalid input in field 'labels'

es scheint der default für die labels als leeres array schuld zu sein. das wird beim post request zu einen "labels":[] laut api doku ist aber nur ein leeres assoziatives array zulässig, also ein "labels": {}

**Comment by LKaemmerling** [comment]
Vielen Dank, der Fehler ist im aktuellen Master behoben!
