### ISSUE TITLE
Upgrade tightenco/collect to v8

### ISSUE THREAD

**Issue by ThomasLandauer** [LKDevelopment/hetzner-cloud-php-sdk#79]
See https://github.com/tighten/collect

**Comment by ThomasLandauer** [comment]
In PHP 8.1, `tightenco/collect` is throwing a bunch of deprecation warnings, so this is getting more urgent now. Since the package isn't maintained anymore, it's probably best to get rid of it completely ;-)

**Comment by ThomasLandauer** [comment]
Ping @LKaemmerling `vimeo/psalm` v4.14.0 is now crashing with:
> PHP Fatal error:  During inheritance of ArrayAccess: Uncaught RuntimeException: PHP Error: Return type of Tightenco\Collect\Support\Collection::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in vendor/tightenco/collect/src/Collect/Support/Collection.php:1789 in vendor/vimeo/psalm/src/Psalm/Internal/ErrorHandler.php:66

As a workaround, I had to add the stated `#[\ReturnTypeWillChange]` attribute at 7 places in that file (`Collection.php`). So this dependency makes your library more and more unusable!

**Comment by LKaemmerling** [comment]
Hey @ThomasLandauer,

thank you for your issue. I just released v2.5.1 which fixes the issue.

**Comment by ThomasLandauer** [comment]
Great, thanks! But since the entire package is deprecated, it would be even better to remove it completely. What are you using it for?

**Comment by LKaemmerling** [comment]
tightenco/collect was removed with the last release.
