### ISSUE TITLE
Add support for primary public IP

### ISSUE THREAD

**Issue by matteobaldassin** [LKDevelopment/hetzner-cloud-php-sdk#86]
Hi, do you plan add support for the new feature released by Hetzner Cloud API?

Reference: https://docs.hetzner.cloud/#primary-ips

**Comment by LKaemmerling** [comment]
Hey @matteobaldassin,

yes the plan to add support is there, how ever I currently have not that big time to do it in the next few weeks. If you want you can try to contribute it :)

**Comment by ayacoo** [comment]
@LKaemmerling I would take care of this during Hacktoberfest and add a basic pull request. I orientate myself on "Image" for the models, but still need support for testing later.

**Comment by LKaemmerling** [comment]
@ayacoo sure feel free to do so :) if you need any help just write me then :)

**Comment by LKaemmerling** [comment]
Was implemented by @ayacoo thank you!
